name: CI

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git sudo shellcheck

      - name: Run install script
        run: .bin/install.sh install

      - name: Run ShellCheck
        run: |
          shellcheck -f gcc ~/.zshrc ~/.zsh/rc/* \
            | grep -vE "SC1036|SC1056|SC1070|SC1072|SC1073|SC1083|SC2034|SC2139|SC2148|SC1090|SC1117|SC2206|SC1009|SC2016|SC2046|SC2154" \
            | tee /dev/stderr \
            | wc -l | xargs -I{} test {} -le 1
